/**
 * Insight Domain Model - "What Should I Do Next?"
 *
 * Insights are AI-generated suggestions for teachers about student progress.
 * They help teachers identify who needs attention, celebration, or monitoring.
 *
 * Key Design Principles:
 * - Insights are AI-generated based on student performance data
 * - Teacher actions are tracked separately (see recommendation.ts)
 * - One insight per student per assignment (prioritize highest value)
 * - Observable evidence only (no inferred emotions)
 */

// ============================================
// Insight Types
// ============================================

/**
 * Insight Type - Classification of AI-generated insights
 *
 * - challenge_opportunity: Student shows readiness for extension/deeper learning
 * - celebrate_progress: Notable improvement or achievement worth recognizing
 * - check_in: Student may benefit from teacher conversation or support
 * - monitor: Situation worth watching but no immediate action needed
 */
export type InsightType =
  | "challenge_opportunity"
  | "celebrate_progress"
  | "check_in"
  | "monitor";

/**
 * Priority Level - Urgency of the insight
 */
export type InsightPriority = "low" | "medium" | "high";

/**
 * Insight Status - Workflow state tracking
 *
 * - pending_review: New insight, awaiting teacher attention
 * - action_taken: Teacher has taken action on this insight
 * - dismissed: Teacher dismissed without action
 * - monitoring: Teacher is actively monitoring this situation
 */
export type InsightStatus =
  | "pending_review"
  | "action_taken"
  | "dismissed"
  | "monitoring";

// ============================================
// Core Insight Interface
// ============================================

/**
 * Insight - AI-generated suggestion for teacher action
 *
 * The core entity of the "What Should I Do Next?" system.
 * Generated by AI based on student performance data.
 */
export interface Insight {
  id: string;

  // Relationships
  studentId: string; // Which student this insight is about
  assignmentId?: string; // Optional: specific assignment context
  classId: string; // Which class context
  subject?: string; // Optional: subject area

  // Classification
  type: InsightType;
  priority: InsightPriority;
  confidence: number; // 0.0 to 1.0 - AI confidence score

  // Content
  summary: string; // Brief, teacher-actionable summary
  evidence: string[]; // Observable data points supporting this insight
  suggestedActions: string[]; // Specific actions teacher can take

  // Workflow
  status: InsightStatus;
  createdAt: Date;
  reviewedAt?: Date;
  reviewedBy?: string; // teacherId who reviewed
}

// ============================================
// Input/Output Types
// ============================================

/**
 * Input for creating a new insight
 */
export interface CreateInsightInput {
  studentId: string;
  assignmentId?: string;
  classId: string;
  subject?: string;
  type: InsightType;
  priority: InsightPriority;
  confidence: number;
  summary: string;
  evidence: string[];
  suggestedActions: string[];
}

/**
 * Input for updating insight status
 */
export interface UpdateInsightStatusInput {
  status: InsightStatus;
  reviewedBy?: string;
}

/**
 * Filter options for querying insights
 */
export interface InsightFilter {
  studentId?: string;
  classId?: string;
  assignmentId?: string;
  subject?: string;
  type?: InsightType;
  types?: InsightType[];
  priority?: InsightPriority;
  priorities?: InsightPriority[];
  status?: InsightStatus;
  statuses?: InsightStatus[];
  minConfidence?: number;
  createdAfter?: Date;
  createdBefore?: Date;
  reviewedBy?: string;
}

/**
 * Sort options for insights
 */
export interface InsightSortOptions {
  field: "createdAt" | "priority" | "confidence" | "type";
  direction: "asc" | "desc";
}

// ============================================
// Aggregation Types
// ============================================

/**
 * Summary of insights for a student
 */
export interface StudentInsightSummary {
  studentId: string;
  studentName: string;
  totalInsights: number;
  pendingCount: number;
  byType: Record<InsightType, number>;
  byPriority: Record<InsightPriority, number>;
  lastInsightAt?: Date;
  badgesEarned?: number;
}

/**
 * Summary of insights for a class
 */
export interface ClassInsightSummary {
  classId: string;
  className: string;
  totalInsights: number;
  pendingCount: number;
  byType: Record<InsightType, number>;
  studentsWithInsights: number;
  totalStudents: number;
  lastInsightAt?: Date;
}

// ============================================
// Response Types
// ============================================

/**
 * Paginated list response for insights
 */
export interface InsightListResponse {
  insights: Insight[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

/**
 * Dashboard data for insight overview
 */
export interface InsightDashboard {
  pendingInsights: Insight[];
  pendingCount: number;
  byType: Record<InsightType, number>;
  byPriority: Record<InsightPriority, number>;
  studentsNeedingAttention: {
    studentId: string;
    studentName: string;
    insightCount: number;
    highestPriority: InsightPriority;
    primaryType: InsightType;
  }[];
  recentActions: any[]; // Will be filled by TeacherActionStore
  celebrationOpportunities: Insight[];
  generatedAt: Date;
}

// ============================================
// Configuration
// ============================================

export const INSIGHT_CONFIG = {
  // Minimum confidence to surface an insight
  MIN_CONFIDENCE: 0.7,

  // Maximum pending insights to show on dashboard
  MAX_DASHBOARD_INSIGHTS: 10,

  // Priority order for sorting (higher index = higher priority)
  TYPE_PRIORITY_ORDER: [
    "monitor",
    "celebrate_progress",
    "challenge_opportunity",
    "check_in",
  ] as InsightType[],

  // Auto-archive insights after this many days
  AUTO_ARCHIVE_DAYS: 30,
};

// ============================================
// Type Guards
// ============================================

export function isInsightType(value: string): value is InsightType {
  return ["challenge_opportunity", "celebrate_progress", "check_in", "monitor"].includes(value);
}

export function isInsightPriority(value: string): value is InsightPriority {
  return ["low", "medium", "high"].includes(value);
}

export function isInsightStatus(value: string): value is InsightStatus {
  return ["pending_review", "action_taken", "dismissed", "monitoring"].includes(value);
}

// ============================================
// Helper Functions
// ============================================

/**
 * Create a new insight with defaults
 */
export function createInsight(input: CreateInsightInput): Insight {
  return {
    id: "", // Should be set by store
    ...input,
    status: "pending_review",
    createdAt: new Date(),
  };
}

/**
 * Check if an insight requires attention
 */
export function requiresAttention(insight: Insight): boolean {
  return insight.status === "pending_review" || insight.status === "monitoring";
}

/**
 * Get display label for insight type
 */
export function getInsightTypeLabel(type: InsightType): string {
  const labels: Record<InsightType, string> = {
    challenge_opportunity: "Challenge Opportunity",
    celebrate_progress: "Celebrate Progress",
    check_in: "Check In",
    monitor: "Monitor",
  };
  return labels[type];
}

/**
 * Get display label for priority
 */
export function getPriorityLabel(priority: InsightPriority): string {
  const labels: Record<InsightPriority, string> = {
    low: "Low",
    medium: "Medium",
    high: "High",
  };
  return labels[priority];
}
