/**
 * Deterministic math problem metadata.
 *
 * Generated by code (not by LLM), attached to Prompt, never shown to students.
 * Used by the coach, evaluator, and deterministic validator to check
 * answers without LLM involvement.
 */

/** Supported deterministic math problem skill types. */
export type MathProblemSkill =
  | "two_digit_addition"
  | "two_digit_subtraction"
  | "basic_multiplication"
  | "place_value";

/** A common wrong answer with its associated misconception. */
export interface CommonWrongAnswer {
  answer: number;
  misconception: string;
}

/** Hidden metadata for a deterministic math problem. */
export interface MathProblem {
  /** The skill being practiced. */
  skill: MathProblemSkill;
  /** First operand (or the number under analysis for place_value). */
  a: number;
  /** Second operand (undefined for place_value). */
  b?: number;
  /** Human-readable expression string (e.g., "27 + 36"). */
  expression: string;
  /** The correct numeric answer. */
  correctAnswer: number;
  /** Whether this problem requires regrouping/borrowing. */
  requiresRegrouping: boolean;
  /** Strategy tags the student should exhibit (e.g., ["add ones", "carry", "add tens"]). */
  expectedStrategyTags: string[];
  /** Common wrong answers with misconception labels. */
  commonWrongAnswers?: CommonWrongAnswer[];
  /** For place_value: which place is being asked about. */
  targetPlace?: "ones" | "tens" | "hundreds";
}
