export type PromptType = "explain" | "generate" | "analyze" | "refactor";

/**
 * Topic-scope metadata for a prompt. Constrains coach follow-ups
 * to stay within the prompt's subject area.
 *
 * Can be:
 * - Authored in lesson JSON (highest priority)
 * - Generated by LLM at lesson-build time and cached
 * - Built heuristically from prompt.input as a last resort
 */
export interface PromptScope {
    /** Keywords the coach should stay near (10–25). */
    allowedKeywords: string[];
    /** Common drift terms the coach should NOT pursue (10–25). */
    offScopeKeywords: string[];
    /** Deterministic redirect probes when coach drifts off-scope (5–10). */
    scopeAlignedProbes: string[];
    /** Primary probes — core on-topic follow-ups. Preferred over secondary. */
    scopeAlignedProbesPrimary?: string[];
    /** Secondary probes — bridge topics allowed at most once (e.g., plants for solar system). */
    scopeAlignedProbesSecondary?: string[];
    /** Keywords that mark secondary/bridge topics. Once mentioned, block further secondary probes. */
    bridgeOnceKeywords?: string[];
    /** Optional topic tags for categorization. */
    topicTags?: string[];
}

/** Assessment & mastery metadata for a prompt. */
export interface PromptAssessment {
    /** What the student should understand or be able to do after answering. */
    learningObjective?: string;
    /** Observable indicators that the student has met the objective. */
    successCriteria?: string[];
    /** Common wrong ideas students may hold (for evaluator awareness). */
    misconceptions?: string[];
    /** Which evaluation dimensions to emphasize when scoring this prompt. */
    evaluationFocus?: EvaluationFocusArea[];
}

export type EvaluationFocusArea =
    | "understanding"
    | "reasoning"
    | "evidence"
    | "clarity"
    | "creativity";

export interface Prompt {
    id: string;
    type: PromptType;
    input: string;
    expectedOutput?: string;
    hints?: string[];
    /** Optional topic-scope metadata. If present, used directly by guardrails. */
    scope?: PromptScope;
    /** Optional assessment & mastery settings for evaluator guidance. */
    assessment?: PromptAssessment;
}